// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDioKDuxrKnut_r8jFpyrTM4iSd58YydEM',
    appId: '1:536635263929:web:0483416fd5ac69eec90468',
    messagingSenderId: '536635263929',
    projectId: 'language-4d26b',
    authDomain: 'language-4d26b.firebaseapp.com',
    storageBucket: 'language-4d26b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyIp9Yi25b9lBfeHoEYvJVG00FPj6ueY',
    appId: '1:536635263929:android:a3b42d742c2d6740c90468',
    messagingSenderId: '536635263929',
    projectId: 'language-4d26b',
    storageBucket: 'language-4d26b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojpNCliaiGxYKVXwAP53C1RAptub-V4o',
    appId: '1:536635263929:ios:e55cc1f8e2fcc529c90468',
    messagingSenderId: '536635263929',
    projectId: 'language-4d26b',
    storageBucket: 'language-4d26b.firebasestorage.app',
    iosBundleId: 'com.example.datapollex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBojpNCliaiGxYKVXwAP53C1RAptub-V4o',
    appId: '1:536635263929:ios:e55cc1f8e2fcc529c90468',
    messagingSenderId: '536635263929',
    projectId: 'language-4d26b',
    storageBucket: 'language-4d26b.firebasestorage.app',
    iosBundleId: 'com.example.datapollex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDioKDuxrKnut_r8jFpyrTM4iSd58YydEM',
    appId: '1:536635263929:web:efc19d633ac28722c90468',
    messagingSenderId: '536635263929',
    projectId: 'language-4d26b',
    authDomain: 'language-4d26b.firebaseapp.com',
    storageBucket: 'language-4d26b.firebasestorage.app',
  );
}
